version: '3.8'

services:
  db:
    container_name: mywallets-db
    platform: linux/x86_64
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${MYWALLETS_DB_NAME:-mywallets-database}
    volumes:
      - db_data:/var/lib/mysql
  backend:
    container_name: mywallets-backend
    restart: always
    build: backend/.
    ports:
      - 8080:8080
    environment:
      EXECUTE_TYPE: rest
      DB_NAME: ${MYWALLETS_DB_NAME:-mywallets-database}
      DB_HOST: mywallets-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      - db
    command: ["wait-for-it", "mywallets-db:3306", "--", "./main"]
  wallettimeline:
    container_name: mywallets-wallettimeline
    restart: always
    build: wallettimeline/.
    ports:
      - 8081:8080
    environment:
      WALLET_TIMELINE_PORT: 8080
      DB_NAME: ${MYWALLETS_DB_NAME:-mywallets-database}
      DB_HOST: mywallets-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      - db
    command: ["wait-for-it", "mywallets-db:3306", "--",
              "/usr/bin/java", "-jar" , "target/wallettimeline-0.0.1-SNAPSHOT.jar"]
  frontend:
    container_name: mywallets-frontend
    restart: always
    build: frontend/.
    ports:
      - 3000:3000

volumes:
  db_data:
