version: '3.8'

services:
  db:
    container_name: mywallets-db
    platform: linux/x86_64
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${MYWALLETS_DB_NAME:-mywallets-database}
    volumes:
      - db_data:/var/lib/mysql
  backend:
    container_name: mywallets-backend
    restart: always
    build: backend/.
    ports:
      - 8080:8080
    environment:
      DB_NAME: ${MYWALLETS_DB_NAME:-mywallets-database}
      DB_HOST: mywallets-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
    command: /app/main

volumes:
  db_data:
